<?php

namespace AppBundle\Repository;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data)
    {
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.id', 'DESC');

        if (!empty($data['category'])) {
            $qb->andWhere('p.category = :cat')->setParameter('cat', $data['category']);
        }
        if (!empty($data['operation'])) {
            $qb->andWhere('p.operation = :op')->setParameter('op', $data['operation']);
        }
        if (!empty($data['surface'])) {
            $qb->andWhere('p.surface <= :surface')->setParameter('surface', $data['surface']);
        }
        if (!empty($data['price'])) {
            $qb->andWhere('p.price <= :price')->setParameter('price', $data['price']);
        }
        if (!empty($data['ville'])) {
            $qb->andWhere('p.ville= :ville')->setParameter('ville', $data['ville']);
        }
        if (!empty($data['region'])) {
            $qb->andWhere('p.region = :region')->setParameter('region', $data['region']);
        }
        if (!empty($data['roomNumber'])) {
            $qb->andWhere('p.roomNumber = :room')->setParameter('room', $data['roomNumber']);
        }

        return $qb; // on fait return $qb quand on utilise le KnpPginatorBundle
    }

    public function latestProperties()
    {
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.image', 'i')
            ->where('p.activate = 1')
            ->setFirstResult(0)
            ->setMaxResults(9)
            ->orderBy('p.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}