region_index:
    path:     /
    defaults: { _controller: "AppBundle:BackOffice/Region:index" }
    methods:  GET

region_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:BackOffice/Region:show" }
    methods:  GET

region_new:
    path:     /new
    defaults: { _controller: "AppBundle:BackOffice/Region:new" }
    methods:  [GET, POST]

region_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:BackOffice/Region:edit" }
    methods:  [GET, POST]

region_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:BackOffice/Region:delete" }
    methods:  DELETE

region_chercher:
    path:     /recherche
    defaults: { _controller: "AppBundle:BackOffice/Region:recherche" }
    methods:  GET